CREATE TABLE USUARIO (
    id INTEGER PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL,
    perfil VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE CATEGORIA (
    id INTEGER PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE LIVRO (
    id INTEGER PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    autor VARCHAR(180) NOT NULL,
    isbn VARCHAR(30) UNIQUE,
    editora VARCHAR(150),
    ano_publicacao INTEGER,
    categoria_id INTEGER NOT NULL,
    FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(id)
);

CREATE TABLE EXEMPLAR (
    id INTEGER PRIMARY KEY,
    livro_id INTEGER NOT NULL,
    tombo VARCHAR(60) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'DISPONIVEL',
    FOREIGN KEY (livro_id) REFERENCES LIVRO(id)
);

CREATE TABLE EMPRESTIMO (
    id INTEGER PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    exemplar_id INTEGER NOT NULL,
    data_emprestimo DATE NOT NULL,
    data_prevista_devolucao DATE NOT NULL,
    data_devolucao DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
    renovacoes INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (usuario_id) REFERENCES USUARIO(id),
    FOREIGN KEY (exemplar_id) REFERENCES EXEMPLAR(id)
);

CREATE TABLE RESERVA (
    id INTEGER PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    livro_id INTEGER NOT NULL,
    data_reserva TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ATIVA',
    FOREIGN KEY (usuario_id) REFERENCES USUARIO(id),
    FOREIGN KEY (livro_id) REFERENCES LIVRO(id)
);

CREATE TABLE MULTA (
    id INTEGER PRIMARY KEY,
    emprestimo_id INTEGER NOT NULL UNIQUE,
    valor DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    data_criacao TIMESTAMP NOT NULL,
    FOREIGN KEY (emprestimo_id) REFERENCES EMPRESTIMO(id)
);
